exports.banks = [
    {
        cid: "776279",
        package: "Sample",
        isbn: "1111123456789",
        name: "MedEd_Sample_Bank",
        description: "MedEd Sample Bank",
        path: "~/Downloads/MEDED_MedEdSample_v19_1111123456789_MedEd",
        taxonomies: {
            "MedEd Test Sample": [
                "Sample",
                "AMEE"
            ]
        }
    },
    {
        cid: "776259",
        package: "UK",
        isbn: "1111222222222",
        name: "UK_Basic_Science",
        description: "UK Basic Science",
        path: "~/Downloads/MEDED_UKBasicScience_v47_1111222222222_MedEd",
        taxonomies: {
            "UK Basic Sciences - Systems": [
                "Cardiovascular system",
                "Endocrine system",
                "Gastrointestinal system",
                "Haematological system",
                "Immune system",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer tissue"
            ],
            "UK Basic Sciences - Disciplines": [
                "Anatomy",
                "Biochemistry",
                "Cell biology",
                "Embryology",
                "Energy metabolism",
                "Epidemiology",
                "Genetics",
                "Histology",
                "Immunology",
                "Microbiology",
                "Molecular biology",
                "Neurology",
                "Nutrition",
                "Pathology",
                "Pathophysiology",
                "Pharmacology/Therapeutics",
                "Physiology",
                "Public health"
            ]
        }
    },
    {
        cid: "776259",
        package: "UK",
        isbn: "1111333333333",
        name: "UK_Clinical_Medicine",
        description: "UK Clinical Medicine",
        path: "~/Downloads/MEDED_UKClinicalMedicine_v61_1111333333333_MedEd",
        taxonomies: {
            "UK Clinical Medicine - Systems": [
                "Cardiovascular system",
                "Endocrine system",
                "Gastrointestinal system",
                "Haematological system",
                "Immune system",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer tissue"
            ],
            "UK Clinical Medicine - Specialties": [
                "Anaesthetics",
                "Dermatology",
                "Emergency Medicine",
                "Endocrinology",
                "ENT",
                "Gastroenterology",
                "General Medicine",
                "Haematology",
                "Infectious Diseases",
                "Molecular Biology/Genetics",
                "Obstetrics and Gynaecology",
                "Ophthalmology",
                "Orthopaedics",
                "Paediatrics",
                "Pathology/Immunology",
                "Psychiatry",
                "Rheumatology",
                "Surgery"
            ],
            "UK Clinical Medicine - Competencies": [
                "Communication Skills",
                "Ethics",
                "Interpretation of Results",
                "Investigation",
                "Making a Diagnosis/decision",
                "Management",
                "Mechanisms of Disease",
                "Peri-Operative Care",
                "Prevention",
                "Prognosis",
                "Symptoms and Signs"
            ]
        }
    },
    {
        cid: "776277",
        package: "USMLE1",
        isbn: "1111444444441",
        name: "USMLE_Step1",
        description: "USMLE Step1",
        path: "~/Downloads/MEDED_USMLEStep1_v31_1111444444441_MedEd",
        taxonomies: {
            "Organ Systems": [
                "Cardiovascular system",
                "Endocrine and Metabolic disorders system",
                "Gastrointestinal system",
                "General system",
                "Hematopoietic/Lymphoid system",
                "Immune system",
                "Musculoskeletal system",
                "Pulmonary/Respiratory system",
                "Nervous system",
                "Psychopathology system",
                "Renal/Urinary system",
                "Reproductive system",
                "Skin/Connective system"
            ],
            "Step 1: Disciplines": [
                "Step 1: Disciplines",
                "Behavioral science",
                "Biochemistry and Nutrition",
                "Biostatistics",
                "Cell biology",
                "Embryology",
                "Genetics",
                "Gross anatomy",
                "Histology",
                "Immunology",
                "Microbiology",
                "Molecular biology",
                "Neuroscience",
                "Physiology",
                "Pathology",
                "Pathophysiology",
                "Pharmacology/Therapeutics"
            ],
            "Step 1: Physician Task": [
                "Applying foundational science concepts",
                "Diagnosis",
                "Management",
                "Evidence-Based Medicine"
            ]
        },
        keyTopicCatalogs: ["Subcategory 1 tested", "Subcategory 2 tested"]
    },
    {
        cid: "776278",
        package: "USMLE2",
        isbn: "1111444444442",
        name: "USMLE_Step2",
        description: "USMLE Step2",
        path: "~/Downloads/MEDED_USMLEStep2_v28_1111444444442_MedEd",
        taxonomies: {
            "Normal Conditions and Disease Categories": [
                "Immune",
                "Blood & Lymphoreticular System",
                "Behavioral Health",
                "Nervous System and Special Senses",
                "Musculoskeletal System",
                "Skin/Subcutaneous Tissue",
                "Cardiovascular System",
                "Respiratory System",
                "Gastrointestinal System",
                "Renal & Urinary Systems & Male Reproductive",
                "Pregnancy, Childbirth & the Puerperium",
                "Female Reproductive & Breast",
                "Endocrine System",
                "Multisystem Processes & Disorders",
                "General Principles of Foundational Science",
                "Biostatistics & Epidemiology/Population Health",
                "Interpretation of the Medical Literature"
            ],
            "Core Clinical Science": [
                "Medicine",
                "Neuroscience",
                "Obstetrics & Gynecology",
                "Pediatrics",
                "Psychiatry",
                "Surgery"
            ],
            "Step2: Physician Task": [
                "Applying Foundational Science Concepts",
                "Diagnosis",
                "Health Maint, Prevention & Surveillance",
                "Pharmacotherapy, Intervention, & Management"
            ]
        },
        keyTopicCatalogs: ["Chief complaint", "Primary disease"]
    },
    {
        cid: "776274",
        package: "ESES",
        isbn: "1111555555551",
        name: "ESES_Basic_Science",
        description: "ESES Basic Science",
        path: "~/Downloads/MEDED_ESESBasicScience_v2_1111555555551_MedEd",
        taxonomies: {
            "ESES Basic Sciences - Systems": [
                "Aparato digestivo",
                "Aparato reproductor",
                "Aparato respiratorio",
                "Metabolismo energético",
                "Sistema circulatorio y cardiovascular",
                "Sistema endocrino",
                "Sistema hematopoyético",
                "Sistema inmunitario",
                "Sistema musculoesquelético",
                "Sistema nefrourinario",
                "Sistema nervioso y órganos de los sentidos",
                "Sistema tegumentario/ piel",
                "Todos/ninguno"
            ],
            "ESES Basic Sciences - Disciplines": [
                "Anatomía",
                "Anatomía Patológica",
                "Bioética",
                "Biología celular y molecular",
                "Bioquímica básica",
                "Bioquímica clínica",
                "Embriología",
                "Epidemiología y bioestadística",
                "Farmacología",
                "Física médica",
                "Fisiología",
                "Genética",
                "Histología",
                "Inmunología",
                "Investigación",
                "Metabolismo energético",
                "Microbiología",
                "Neuroanatomía y Neurociencias",
                "Patología",
                "Propedeutica y semiología"
            ]
        }
    },
    {
        cid: "776274",
        package: "ESES",
        isbn: "1111555555552",
        name: "ESES_Clinical_Medicine",
        description: "ESES Clinical Medicine",
        path: "~/Downloads/MEDED_ESESClinicalMedicine_v2_1111555555552_MedEd",
        taxonomies: {
            "ESES Clinical Medicine - Systems": [
                "Aparato cardiovascular",
                "Aparato digestivo",
                "Aparato locomotor",
                "Aparato reproductor",
                "Aparato respiratorio",
                "Sistema circulatorio y cardiovascular",
                "Sistema endocrino",
                "Sistema hematológico",
                "Sistema hematopoyético",
                "Sistema inmunitario",
                "Sistema musculoesquelético",
                "Sistema nefrourinario",
                "Sistema nervioso",
                "Sistema nervioso y órganos de los sentidos",
                "Sistema renal/urinario",
                "Sistema tegumentario/ piel",
                "Tejido cutáneo/neoplásico",
                "Todos/ninguno"
            ],
            "ESES Clinical Medicine - Specialties": [
                "Alergología",
                "Análisis clínicos",
                "Anatomía Patológica",
                "Anatomía patológica/inmunología",
                "Anestesia",
                "Anestesiología, reanimación y medicina del dolor",
                "Cardiología",
                "Cirugía",
                "Cuidados paliativos",
                "Dermatología",
                "Educación médica",
                "Endocrinología",
                "Endocrinología, metabolismo y nutrición",
                "Enfermedades infecciosas",
                "Gastroenterología",
                "Gastroenterología y hepatología",
                "Geriatría y gerontología",
                "Ginecología y obstetricia",
                "Hematología",
                "Medicina de urgencias",
                "Medicina de urgencias y emergencias",
                "Medicina Familiar y comunitaria",
                "Medicina general",
                "Medicina Interna",
                "Medicina Legal y forense",
                "Medicina preventiva y salud pública",
                "Neumología",
                "Neurología",
                "Obstetricia y Ginecología",
                "Oftalmología",
                "Oncología",
                "Otorrinolaringología",
                "Pediatría",
                "Psiquiatría",
                "Radiología y diagnóstico por imagen",
                "Reumatología",
                "Traumatología, Ortopedia y rehabilitación",
                "Urología y Nefrología"
            ],
            "ESES Clinical Medicine - Competencies": [
                "Communication Skills",
                "Ethics",
                "Interpretation of Results",
                "Investigation",
                "Making a Diagnosis/decision",
                "Management",
                "Mechanisms of Disease",
                "Peri-Operative Care",
                "Prevention",
                "Prognosis",
                "Symptoms and Signs"
            ]
        }
    },
    {
        cid: "776273",
        package: "ANZ",
        isbn: "1111777777771",
        name: "ANZ_Basic_Science",
        description: "ANZ Basic Science",
        path: "~/Downloads/MEDED_ANZBasicScience_v9_1111777777771_MedEd",
        taxonomies: {
            "UK Basic Sciences - Systems": [
                "Cardiovascular system",
                "Endocrine system",
                "Gastrointestinal system",
                "Haematological system",
                "Immune system",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer tissue"
            ],
            "UK Basic Sciences - Disciplines": [
                "Anatomy",
                "Biochemistry",
                "Cell biology",
                "Embryology",
                "Energy metabolism",
                "Epidemiology",
                "Genetics",
                "Histology",
                "Immunology",
                "Microbiology",
                "Molecular biology",
                "Neurology",
                "Nutrition",
                "Pathology",
                "Pathophysiology",
                "Pharmacology/Therapeutics",
                "Physiology",
                "Public health"
            ]
        }
    },
    {
        cid: "776273",
        package: "ANZ",
        isbn: "1111777777772",
        name: "ANZ_Clinical_Medicine",
        description: "ANZ Clinical Medicine",
        path: "~/Downloads/MEDED_ANZClinicalMedicine_v8_1111777777772_MedEd",
        taxonomies: {
            "UK Clinical Medicine - Systems": [
                "Cardiovascular system",
                "Endocrine system",
                "Gastrointestinal system",
                "Haematological system",
                "Immune system",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer tissue"
            ],
            "UK Clinical Medicine - Specialties": [
                "Anaesthetics",
                "Dermatology",
                "Emergency Medicine",
                "Endocrinology",
                "ENT",
                "Gastroenterology",
                "General Medicine",
                "Haematology",
                "Infectious Diseases",
                "Molecular Biology/Genetics",
                "Obstetrics and Gynaecology",
                "Ophthalmology",
                "Orthopaedics",
                "Paediatrics",
                "Pathology/Immunology",
                "Psychiatry",
                "Rheumatology",
                "Surgery"
            ],
            "UK Clinical Medicine - Competencies": [
                "Communication Skills",
                "Ethics",
                "Interpretation of Results",
                "Investigation",
                "Making a Diagnosis/decision",
                "Management",
                "Mechanisms of Disease",
                "Peri-Operative Care",
                "Prevention",
                "Prognosis",
                "Symptoms and Signs"
            ]
        }
    },
    {
        cid: "776271",
        package: "IND",
        isbn: "1111888888881",
        name: "IND_Basic_Science",
        description: "IND Basic Science",
        path: "~/Downloads/MEDED_INDBasicScience_v5_1111888888881_MedEd",
        taxonomies: {
            "IND Basic Sciences - Systems": [
                "Basic sciences application in clinical context",
                "Cardiovascular system",
                "Endocrine system",
                "Energy metabolism",
                "Gastrointestinal system",
                "General",
                "Haematological system",
                "Immune system",
                "Knowledge",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer Tissue"
            ],
            "IND Basic Sciences - Disciplines": [
                "Anatomy",
                "Biochemistry",
                "Community Medicine",
                "Forensic Medicine",
                "Microbiology",
                "Pathology",
                "Pharmacology/Toxicology",
                "Physiology"
            ]
        }
    },
    {
        cid: "776271",
        package: "IND",
        isbn: "1111888888882",
        name: "IND_Clinical_Medicine",
        description: "IND Clinical Medicine",
        path: "~/Downloads/MEDED_INDClinicalMedicine_v5_1111888888882_MedEd",
        taxonomies: {
            "IND Clinical Medicine - Systems": [
                "Cardiovascular system",
                "Endocrine system",
                "Gastrointestinal system",
                "Haematological system",
                "Immune system",
                "Musculoskeletal system",
                "Nervous system",
                "Psychological system",
                "Renal/Urinary system",
                "Reproductive system",
                "Respiratory system",
                "Skin/Cancer tissue"
            ],
            "IND Clinical Medicine - Specialties": [
                "Anesthesia",
                "Dermatology",
                "ENT",
                "Medicine",
                "Obstetrics and Gynaecology",
                "Ophthalmology",
                "Orthopaedics",
                "Paediatrics",
                "Psychiatry",
                "Radiology",
                "Surgery"
            ],
            "IND Clinical Medicine - Competencies": [
                "Communication Skills",
                "Ethics",
                "Interpretation of Results",
                "Investigation",
                "Making a Diagnosis/decision",
                "Management",
                "Mechanisms of Disease",
                "Peri-Operative Care",
                "Prevention",
                "Prognosis",
                "Symptoms and Signs"
            ]
        }
    },
    {
        cid: "776272",
        package: "BRA",
        isbn: "1111666666661",
        name: "BRA_Basic_Science",
        description: "BRA Basic Science",
    },
    {
        cid: "776272",
        package: "BRA",
        isbn: "1111666666662",
        name: "BRA_Clinical_Medicine",
        description: "BRA Clinical Medicine",
    },
    {
        cid: "776269",
        package: "FR",
        isbn: "1111999999991",
        name: "FR_Basic_Science",
        description: "FR Basic Science",
    },
    {
        cid: "776269",
        package: "FR",
        isbn: "1111999999992",
        name: "FR_Clinical_Medicine",
        description: "FR Clinical Medicine",
    },
    {
        cid: "776270",
        package: "DE",
        isbn: "1111000000001",
        name: "DE_Basic_Science",
        description: "DE Basic Science",
    },
    {
        cid: "776270",
        package: "DE",
        isbn: "1111000000002",
        name: "DE_Clinical_Medicine",
        description: "DE Clinical Medicine",
    }
];
